# Generated by Django 5.1.3 on 2025-02-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0002_hobby_user_hobbies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="django_backend.project"
            ),
        ),
    ]
