# Generated by Django 5.1.3 on 2025-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0005_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employmentStatuses", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="employmentStatuses",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="django_backend.employmentstatus"
            ),
        ),
    ]
