# Generated by Django 5.1.3 on 2025-02-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0006_employmentstatus_user_employmentstatuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.ManyToManyField(blank=True, related_name='users', to='django_backend.profession'),
        ),
    ]
