# Generated by Django 5.1.3 on 2025-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0007_profession_user_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.ManyToManyField(blank=True, related_name='users', to='django_backend.industry'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='users', to='django_backend.position'),
        ),
    ]
