# Generated by Django 5.1.3 on 2025-03-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0008_industry_position_user_industry_user_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="project",
        ),
        migrations.AddField(
            model_name="project",
            name="forms",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="django_backend.form"
            ),
        ),
    ]
