# Generated by Django 5.1.3 on 2025-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0009_remove_form_project_project_forms"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_group", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="age_group",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="django_backend.agegroup"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gender",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="django_backend.gender"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="interest",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="django_backend.interest"
            ),
        ),
    ]
