# Generated by Django 5.1.3 on 2025-03-06 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0011_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_backend.user",
            ),
        ),
    ]
