# Generated by Django 5.1.3 on 2025-03-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0012_alter_question_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsabilityTesting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("task", models.CharField(max_length=500)),
            ],
        ),
    ]
