# Generated by Django 5.1.3 on 2025-03-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0013_usabilitytesting"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="usability_testings",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="django_backend.usabilitytesting",
            ),
        ),
    ]
