# Generated by Django 5.1.3 on 2025-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0014_project_usability_testings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usabilitytesting",
            name="figma_embed_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usabilitytesting",
            name="website_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
