# Generated by Django 5.1.3 on 2025-03-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0015_usabilitytesting_figma_embed_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usabilitytesting",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
