# Generated by Django 4.2.20 on 2025-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0016_usabilitytesting_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsabilityTestRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usability_testing_id", models.IntegerField()),
                ("video", models.FileField(upload_to="recordings/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
