# Generated by Django 4.2.20 on 2025-03-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0017_usabilitytestrecording"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsabilityTestRecordingV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="recordings/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usability_testing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.usabilitytesting",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UsabilityTestRecording",
        ),
    ]
