# Generated by Django 4.2.20 on 2025-03-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0018_usabilitytestrecordingv2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usabilitytestrecordingv2",
            name="usability_testing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recording",
                to="django_backend.usabilitytesting",
            ),
        ),
    ]
