# Generated by Django 4.2.20 on 2025-03-08 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0020_usabilitytestrecordingv3_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="participant",
            new_name="participant_email",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="question",
            name="created_by",
        ),
    ]
