# Generated by Django 5.1.3 on 2025-03-09 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0021_rename_participant_answer_participant_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsabilityTestRecordingV4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="recordings/")),
                (
                    "participant_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.user",
                    ),
                ),
                (
                    "usability_testing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.usabilitytesting",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UsabilityTestRecordingV3",
        ),
    ]
