# Generated by Django 4.2.20 on 2025-03-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0023_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consent",
            name="form",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="django_backend.form"
            ),
        ),
    ]
