# Generated by Django 4.2.20 on 2025-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0024_alter_consent_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
