# Generated by Django 4.2.20 on 2025-03-24 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0025_form_is_shared"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestingConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_text", models.TextField()),
                (
                    "usability_testing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.usabilitytesting",
                    ),
                ),
            ],
        ),
    ]
