# Generated by Django 4.2.20 on 2025-03-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0026_testingconsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="context_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
