# Generated by Django 4.2.20 on 2025-04-03 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0027_project_context_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="context_text",
            new_name="consent_text",
        ),
    ]
