# Generated by Django 4.2.20 on 2025-04-03 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0029_susform_project_susforms"),
    ]

    operations = [
        migrations.CreateModel(
            name="SUSQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "susform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.susform",
                    ),
                ),
            ],
        ),
    ]
