# Generated by Django 4.2.20 on 2025-04-04 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0031_susanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SUSQAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.IntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.user",
                    ),
                ),
                (
                    "susquestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.susquestion",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SUSAnswer",
        ),
    ]
