# Generated by Django 4.2.20 on 2025-04-04 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0032_susqanswer_delete_susanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="susqanswer",
            name="submitted_at",
        ),
    ]
