# Generated by Django 4.2.20 on 2025-04-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0033_remove_susqanswer_submitted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.JSONField(default=list)),
                ("age_group", models.JSONField(default=list)),
                ("interest", models.JSONField(default=list)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.project",
                    ),
                ),
            ],
        ),
    ]
