# Generated by Django 4.2.20 on 2025-04-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0034_projectcriteria"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sad", models.FloatField(blank=True, null=True)),
                ("angry", models.FloatField(blank=True, null=True)),
                ("disgust", models.FloatField(blank=True, null=True)),
                ("fear", models.FloatField(blank=True, null=True)),
                ("happy", models.FloatField(blank=True, null=True)),
                ("surprise", models.FloatField(blank=True, null=True)),
                ("neutral", models.FloatField(blank=True, null=True)),
                ("dominant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "participant_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_backend.user",
                    ),
                ),
                (
                    "usability_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotion_snapshots",
                        to="django_backend.usabilitytesting",
                    ),
                ),
            ],
        ),
    ]
