# Generated by Django 4.2.20 on 2025-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0036_projectcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="image_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="ProjectCategory",
        ),
    ]
