# Generated by Django 4.2.20 on 2025-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0037_project_category_project_image_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="susform",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
