# Generated by Django 4.2.20 on 2025-10-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_backend", "0040_collaboration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usabilitytesting",
            name="task",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
